export type LeadStatus = 'Baru' | 'Kualifikasi' | 'Presentasi' | 'Negosiasi' | 'Menang' | 'Kalah' | 'Ditunda';
export type LeadSource = 'Referral Internal' | 'Pameran & Event' | 'Inbound Website' | 'Cold Outreach' | 'Tender Pemerintah' | 'Rekomendasi Mitra';
export type LeadSegmen = 'Logistik' | 'Migas' | 'Perdagangan' | 'Kepelabuhanan' | 'Utilitas' | 'Industri';
export type LeadPriority = 'Tinggi' | 'Sedang' | 'Rendah';

export interface Lead {
  id: string;
  namaPerusahaan: string;
  kontakUtama: string;
  jabatan: string;
  email: string;
  telepon: string;
  segmen: LeadSegmen;
  region: string;
  source: LeadSource;
  status: LeadStatus;
  priority: LeadPriority;
  skorLead: number; // 0-100
  estimasiNilai: number;
  picInternal: string;
  tanggalMasuk: string;
  lastActivity: string;
  nextAction: string;
  nextActionDate: string;
  catatan: string;
  jenisKontrakTarget: string;
  probabilitas: number; // 0-100%
}

export const leads: Lead[] = [
  {
    id: 'l001',
    namaPerusahaan: 'PT Energi Mega Persada Tbk.',
    kontakUtama: 'Ir. Darmawan Susilo',
    jabatan: 'VP Marine Operations',
    email: 'd.susilo@emp.co.id',
    telepon: '+62 711 445500',
    segmen: 'Migas',
    region: 'Palembang',
    source: 'Tender Pemerintah',
    status: 'Negosiasi',
    priority: 'Tinggi',
    skorLead: 87,
    estimasiNilai: 12500000000,
    picInternal: 'Ahmad Fauzi',
    tanggalMasuk: '2026-01-10',
    lastActivity: '2026-03-12',
    nextAction: 'Presentasi proposal teknis',
    nextActionDate: '2026-03-20',
    catatan: 'Peluang TUKS baru di Palembang. Sudah 2x pertemuan. Keputusan akhir bulan ini.',
    jenisKontrakTarget: 'TUKS',
    probabilitas: 75,
  },
  {
    id: 'l002',
    namaPerusahaan: 'PT Timah Tbk.',
    kontakUtama: 'Drs. Hendra Wijaya',
    jabatan: 'Direktur Logistik',
    email: 'h.wijaya@timah.com',
    telepon: '+62 717 421234',
    segmen: 'Industri',
    region: 'Palembang',
    source: 'Referral Internal',
    status: 'Presentasi',
    priority: 'Tinggi',
    skorLead: 79,
    estimasiNilai: 8200000000,
    picInternal: 'Budi Santoso',
    tanggalMasuk: '2026-01-25',
    lastActivity: '2026-03-10',
    nextAction: 'Kirim draft MoU untuk review',
    nextActionDate: '2026-03-18',
    catatan: 'Referral dari Pusri. Butuh layanan pemanduan kapal timah. Sangat tertarik.',
    jenisKontrakTarget: 'PKS',
    probabilitas: 65,
  },
  {
    id: 'l003',
    namaPerusahaan: 'PT Pelabuhan Tanjung Api-Api',
    kontakUtama: 'Capt. Ridwan Hakim',
    jabatan: 'General Manager',
    email: 'r.hakim@ptaa.co.id',
    telepon: '+62 711 889900',
    segmen: 'Kepelabuhanan',
    region: 'Palembang',
    source: 'Pameran & Event',
    status: 'Kualifikasi',
    priority: 'Tinggi',
    skorLead: 91,
    estimasiNilai: 18000000000,
    picInternal: 'Dewi Rahayu',
    tanggalMasuk: '2026-02-03',
    lastActivity: '2026-03-14',
    nextAction: 'Site visit terminal baru',
    nextActionDate: '2026-03-22',
    catatan: 'Pertemuan di Indonesia Port Expo. Proyek terminal baru senilai besar. Prioritas utama.',
    jenisKontrakTarget: 'Perjanjian Kerjasama',
    probabilitas: 80,
  },
  {
    id: 'l004',
    namaPerusahaan: 'PT Sriwijaya Air Cargo',
    kontakUtama: 'Andi Prasetyo',
    jabatan: 'Head of Logistics',
    email: 'a.prasetyo@sriwijayacargo.co.id',
    telepon: '+62 711 334455',
    segmen: 'Logistik',
    region: 'Palembang',
    source: 'Cold Outreach',
    status: 'Baru',
    priority: 'Sedang',
    skorLead: 52,
    estimasiNilai: 3400000000,
    picInternal: 'Siti Mardiyah',
    tanggalMasuk: '2026-03-01',
    lastActivity: '2026-03-05',
    nextAction: 'Follow-up telepon pertama',
    nextActionDate: '2026-03-17',
    catatan: 'Kontak awal via email. Tertarik layanan gudang dan logistik pelabuhan.',
    jenisKontrakTarget: 'PKS',
    probabilitas: 30,
  },
  {
    id: 'l005',
    namaPerusahaan: 'PT Holcim Indonesia Tbk.',
    kontakUtama: 'Ir. Susanto Wibowo',
    jabatan: 'Supply Chain Director',
    email: 's.wibowo@holcim.co.id',
    telepon: '+62 254 391122',
    segmen: 'Industri',
    region: 'Banten',
    source: 'Rekomendasi Mitra',
    status: 'Negosiasi',
    priority: 'Tinggi',
    skorLead: 83,
    estimasiNilai: 9700000000,
    picInternal: 'Reza Firmansyah',
    tanggalMasuk: '2026-01-18',
    lastActivity: '2026-03-13',
    nextAction: 'Finalisasi klausul harga',
    nextActionDate: '2026-03-19',
    catatan: 'Direkomendasikan Krakatau Steel. Butuh pemanfaatan lahan terminal semen Banten.',
    jenisKontrakTarget: 'Pemanfaatan Lahan',
    probabilitas: 70,
  },
  {
    id: 'l006',
    namaPerusahaan: 'PT Elnusa Petrofin',
    kontakUtama: 'Bambang Nugroho',
    jabatan: 'Operations Manager',
    email: 'b.nugroho@elnusapetrofin.co.id',
    telepon: '+62 711 556677',
    segmen: 'Migas',
    region: 'Jambi',
    source: 'Tender Pemerintah',
    status: 'Kualifikasi',
    priority: 'Sedang',
    skorLead: 68,
    estimasiNilai: 5600000000,
    picInternal: 'Ahmad Fauzi',
    tanggalMasuk: '2026-02-14',
    lastActivity: '2026-03-09',
    nextAction: 'Kirim dokumen pra-kualifikasi',
    nextActionDate: '2026-03-21',
    catatan: 'Tender KKKS Jambi. Persaingan ketat dengan 3 peserta lain.',
    jenisKontrakTarget: 'PKS',
    probabilitas: 45,
  },
  {
    id: 'l007',
    namaPerusahaan: 'PT Aneka Tambang Tbk.',
    kontakUtama: 'Dr. Yusuf Hidayat',
    jabatan: 'VP Mineral Processing',
    email: 'y.hidayat@antam.com',
    telepon: '+62 711 778800',
    segmen: 'Industri',
    region: 'Bengkulu',
    source: 'Referral Internal',
    status: 'Presentasi',
    priority: 'Sedang',
    skorLead: 74,
    estimasiNilai: 6800000000,
    picInternal: 'Dewi Rahayu',
    tanggalMasuk: '2026-02-08',
    lastActivity: '2026-03-11',
    nextAction: 'Demo layanan pemanduan',
    nextActionDate: '2026-03-25',
    catatan: 'Ekspansi terminal mineral Bengkulu. Sudah ada hubungan baik via Bukit Asam.',
    jenisKontrakTarget: 'MoU',
    probabilitas: 55,
  },
  {
    id: 'l008',
    namaPerusahaan: 'PT Barito Pacific Tbk.',
    kontakUtama: 'Ir. Gunawan Santoso',
    jabatan: 'Head of Port Operations',
    email: 'g.santoso@baritopacific.co.id',
    telepon: '+62 711 990011',
    segmen: 'Industri',
    region: 'Palembang',
    source: 'Inbound Website',
    status: 'Baru',
    priority: 'Rendah',
    skorLead: 41,
    estimasiNilai: 2100000000,
    picInternal: 'Siti Mardiyah',
    tanggalMasuk: '2026-03-08',
    lastActivity: '2026-03-08',
    nextAction: 'Kirim company profile',
    nextActionDate: '2026-03-16',
    catatan: 'Inquiry via website. Butuh informasi layanan terminal petrokimia.',
    jenisKontrakTarget: 'PKS',
    probabilitas: 20,
  },
  {
    id: 'l009',
    namaPerusahaan: 'PT Pelayaran Tempuran Emas',
    kontakUtama: 'Capt. Arief Setiawan',
    jabatan: 'Fleet Manager',
    email: 'a.setiawan@temas.co.id',
    telepon: '+62 711 223344',
    segmen: 'Kepelabuhanan',
    region: 'Palembang',
    source: 'Pameran & Event',
    status: 'Menang',
    priority: 'Tinggi',
    skorLead: 95,
    estimasiNilai: 7300000000,
    picInternal: 'Budi Santoso',
    tanggalMasuk: '2025-12-01',
    lastActivity: '2026-03-14',
    nextAction: 'Proses onboarding mitra',
    nextActionDate: '2026-03-20',
    catatan: 'DEAL CLOSED! PKS pemanduan kapal kontainer. Proses onboarding berjalan.',
    jenisKontrakTarget: 'PKS',
    probabilitas: 100,
  },
  {
    id: 'l010',
    namaPerusahaan: 'PT Samudra Indonesia Tbk.',
    kontakUtama: 'Drs. Hadi Purnomo',
    jabatan: 'Commercial Director',
    email: 'h.purnomo@samudra.co.id',
    telepon: '+62 711 667788',
    segmen: 'Kepelabuhanan',
    region: 'Bengkulu',
    source: 'Cold Outreach',
    status: 'Kalah',
    priority: 'Rendah',
    skorLead: 28,
    estimasiNilai: 4500000000,
    picInternal: 'Reza Firmansyah',
    tanggalMasuk: '2025-11-15',
    lastActivity: '2026-02-28',
    nextAction: 'Evaluasi ulang Q3 2026',
    nextActionDate: '2026-07-01',
    catatan: 'Kalah tender ke kompetitor. Harga tidak kompetitif. Evaluasi ulang di Q3.',
    jenisKontrakTarget: 'PKS',
    probabilitas: 0,
  },
  {
    id: 'l011',
    namaPerusahaan: 'PT Indocement Tunggal Prakarsa',
    kontakUtama: 'Ir. Bambang Hartono',
    jabatan: 'Logistics Manager',
    email: 'b.hartono@indocement.co.id',
    telepon: '+62 251 8631234',
    segmen: 'Industri',
    region: 'Banten',
    source: 'Rekomendasi Mitra',
    status: 'Ditunda',
    priority: 'Sedang',
    skorLead: 60,
    estimasiNilai: 5200000000,
    picInternal: 'Reza Firmansyah',
    tanggalMasuk: '2026-01-05',
    lastActivity: '2026-02-20',
    nextAction: 'Re-engage setelah Q2 budget approval',
    nextActionDate: '2026-04-15',
    catatan: 'Ditunda karena freeze anggaran Q1. Akan kembali aktif Q2. Tetap jaga hubungan.',
    jenisKontrakTarget: 'Pemanfaatan Lahan',
    probabilitas: 40,
  },
  {
    id: 'l012',
    namaPerusahaan: 'PT Pertamina Hulu Energi',
    kontakUtama: 'Ir. Wahyu Setiadi',
    jabatan: 'Marine Superintendent',
    email: 'w.setiadi@phe.pertamina.com',
    telepon: '+62 711 445566',
    segmen: 'Migas',
    region: 'Palembang',
    source: 'Referral Internal',
    status: 'Kualifikasi',
    priority: 'Tinggi',
    skorLead: 88,
    estimasiNilai: 14500000000,
    picInternal: 'Ahmad Fauzi',
    tanggalMasuk: '2026-02-20',
    lastActivity: '2026-03-14',
    nextAction: 'Pertemuan teknis dengan tim marine',
    nextActionDate: '2026-03-18',
    catatan: 'Anak perusahaan Pertamina. Referral dari PTK. Potensi nilai sangat besar.',
    jenisKontrakTarget: 'PKS',
    probabilitas: 72,
  },
];

export interface LeadSourceStat {
  source: LeadSource;
  count: number;
  totalNilai: number;
  winRate: number;
  color: string;
}

export function getLeadSourceStats(): LeadSourceStat[] {
  const sources: LeadSource[] = ['Referral Internal', 'Pameran & Event', 'Inbound Website', 'Cold Outreach', 'Tender Pemerintah', 'Rekomendasi Mitra'];
  const colors = ['#1d4ed8', '#f59e0b', '#06b6d4', '#8b5cf6', '#ef4444', '#10b981'];
  return sources.map((src, i) => {
    const srcLeads = leads.filter((l) => l.source === src);
    const won = srcLeads.filter((l) => l.status === 'Menang').length;
    return {
      source: src,
      count: srcLeads.length,
      totalNilai: srcLeads.reduce((s, l) => s + l.estimasiNilai, 0),
      winRate: srcLeads.length > 0 ? Math.round((won / srcLeads.length) * 100) : 0,
      color: colors[i],
    };
  });
}
