export interface Contract {
  id: string;
  nomorKontrak: string;
  mitra: string;
  mitraId: string;
  jenisKontrak: 'MoU' | 'PKS' | 'Perjanjian Kerjasama' | 'Addendum' | 'TUKS' | 'Pemanfaatan Lahan';
  nilaiKontrak: number;
  tarif?: number;
  bentukKerjasama?: 'Sewa' | 'BGS' | 'BSG' | 'KSU' | 'KSO' | 'Pinjam Pakai' | 'Joint Venture' | 'Lainnya';
  tanggalMulai: string;
  tanggalAkhir: string;
  sisaHari: number;
  status: 'Draft' | 'Review Legal' | 'Approval SM/ED' | 'Aktif' | 'Mendekati Akhir' | 'Expired' | 'Renewal';
  complianceScore: number;
  missingClauses: string[];
  picInternal: string;
  region: string;
  kategori: string;
  pnbpValue: number;
  lastUpdated: string;
  keterangan: string;
}

export interface Partner {
  id: string;
  namaPerusahaan: string;
  npwp: string;
  segmenBisnis: 'Logistik' | 'Migas' | 'Perdagangan' | 'Kepelabuhanan' | 'Utilitas' | 'Industri';
  picInternal: string;
  kontrakAktif: number;
  totalNilaiKontrak: number;
  complianceScore: number;
  status: 'Lead' | 'Pra-Kualifikasi' | 'Negosiasi' | 'Mitra Aktif' | 'Evaluasi' | 'Penutupan';
  skorPeluang: number;
  region: string;
  kontakUtama: string;
  jabatanKontak: string;
  email: string;
  telepon: string;
  alamat: string;
  bergabungSejak: string;
  lastInteraction: string;
  ratingK3: 'A' | 'B' | 'C' | 'D';
  totalKontrak: number;
  renewalRate: number;
  catatan: string;
}

export interface ActivityLog {
  id: string;
  timestamp: string;
  type: 'upload' | 'approval' | 'alert' | 'reminder' | 'renewal' | 'create' | 'review';
  title: string;
  description: string;
  user: string;
  kontrakId?: string;
  mitraName?: string;
}

export const contracts: Contract[] = [
  {
    id: 'c001',
    nomorKontrak: 'HK.01/PKS/001/PLND-REG2/2024',
    mitra: 'PetroChina International Jabung Ltd.',
    mitraId: 'p001',
    jenisKontrak: 'PKS',
    nilaiKontrak: 8750000000,
    tanggalMulai: '2024-03-01',
    tanggalAkhir: '2026-03-31',
    sisaHari: 16,
    status: 'Mendekati Akhir',
    complianceScore: 72,
    missingClauses: ['Klausul CSMS', 'Program Fit to Work'],
    picInternal: 'Ahmad Fauzi',
    region: 'Jambi',
    kategori: 'Pemanduan & Penundaan Kapal',
    pnbpValue: 1250000000,
    lastUpdated: '2026-03-10',
    keterangan: 'Kontrak layanan pemanduan kapal tanker di perairan Jambi. Perlu renewal segera.',
  },
  {
    id: 'c002',
    nomorKontrak: 'HK.01/MoU/002/PLND-REG2/2025',
    mitra: 'PT Dok Usaha Sejahtera Bengkulu',
    mitraId: 'p002',
    jenisKontrak: 'MoU',
    nilaiKontrak: 2400000000,
    tanggalMulai: '2025-01-15',
    tanggalAkhir: '2026-04-30',
    sisaHari: 46,
    status: 'Mendekati Akhir',
    complianceScore: 85,
    missingClauses: ['Klausul Audit BPK'],
    picInternal: 'Dewi Rahayu',
    region: 'Bengkulu',
    kategori: 'Pemanfaatan Fasilitas Pelabuhan',
    pnbpValue: 380000000,
    lastUpdated: '2026-03-12',
    keterangan: 'Nota Kesepahaman pemanfaatan fasilitas dermaga Bengkulu. Dasar hukum lengkap.',
  },
  {
    id: 'c003',
    nomorKontrak: 'HK.01/PKS/003/PLND-REG2/2023',
    mitra: 'PT Pertamina Trans Kontinental',
    mitraId: 'p003',
    jenisKontrak: 'PKS',
    nilaiKontrak: 15200000000,
    tanggalMulai: '2023-07-01',
    tanggalAkhir: '2026-06-30',
    sisaHari: 107,
    status: 'Aktif',
    complianceScore: 96,
    missingClauses: [],
    picInternal: 'Budi Santoso',
    region: 'Palembang',
    kategori: 'TUKS (Terminal Untuk Kepentingan Sendiri)',
    pnbpValue: 2850000000,
    lastUpdated: '2026-02-28',
    keterangan: 'PKS TUKS operasional terminal Pertamina. Semua klausul K3 dan GCG terpenuhi.',
  },
  {
    id: 'c004',
    nomorKontrak: 'HK.01/ADD/004/PLND-REG2/2025',
    mitra: 'PT Semen Baturaja (Persero) Tbk.',
    mitraId: 'p004',
    jenisKontrak: 'Addendum',
    nilaiKontrak: 4600000000,
    tanggalMulai: '2025-04-01',
    tanggalAkhir: '2026-12-31',
    sisaHari: 291,
    status: 'Aktif',
    complianceScore: 90,
    missingClauses: [],
    picInternal: 'Siti Mardiyah',
    region: 'Palembang',
    kategori: 'Pemanfaatan Lahan',
    pnbpValue: 620000000,
    lastUpdated: '2026-03-01',
    keterangan: 'Addendum perpanjangan pemanfaatan lahan terminal curah kering.',
  },
  {
    id: 'c005',
    nomorKontrak: 'HK.01/PKS/005/PLND-REG2/2024',
    mitra: 'PT Medco Energi Internasional',
    mitraId: 'p005',
    jenisKontrak: 'PKS',
    nilaiKontrak: 6300000000,
    tanggalMulai: '2024-09-01',
    tanggalAkhir: '2026-04-15',
    sisaHari: 31,
    status: 'Mendekati Akhir',
    complianceScore: 61,
    missingClauses: ['Klausul K3 (SMK3)', 'Klausul HSSE Mitra', 'Audit K3 Berkala'],
    picInternal: 'Ahmad Fauzi',
    region: 'Palembang',
    kategori: 'Pemanduan & Penundaan Kapal',
    pnbpValue: 890000000,
    lastUpdated: '2026-03-08',
    keterangan: 'PKS layanan tunda kapal. KRITIS: 3 klausul K3 wajib belum ada, risiko temuan BPK.',
  },
  {
    id: 'c006',
    nomorKontrak: 'HK.01/PKS/006/PLND-REG2/2025',
    mitra: 'PT Krakatau Steel (Persero) Tbk.',
    mitraId: 'p006',
    jenisKontrak: 'Pemanfaatan Lahan',
    nilaiKontrak: 3900000000,
    tanggalMulai: '2025-02-01',
    tanggalAkhir: '2027-01-31',
    sisaHari: 322,
    status: 'Aktif',
    complianceScore: 88,
    missingClauses: ['Klausul GCG'],
    picInternal: 'Reza Firmansyah',
    region: 'Banten',
    kategori: 'Pemanfaatan Lahan',
    pnbpValue: 510000000,
    lastUpdated: '2026-03-05',
    keterangan: 'Pemanfaatan lahan terminal baja Krakatau. GCG clause perlu update.',
  },
  {
    id: 'c007',
    nomorKontrak: 'HK.01/MoU/007/PLND-REG2/2024',
    mitra: 'PT Bukit Asam Tbk.',
    mitraId: 'p007',
    jenisKontrak: 'MoU',
    nilaiKontrak: 11500000000,
    tanggalMulai: '2024-01-01',
    tanggalAkhir: '2025-12-31',
    sisaHari: -74,
    status: 'Expired',
    complianceScore: 78,
    missingClauses: ['Klausul PNBP', 'Klausul Force Majeure'],
    picInternal: 'Dewi Rahayu',
    region: 'Palembang',
    kategori: 'TUKS (Terminal Untuk Kepentingan Sendiri)',
    pnbpValue: 0,
    lastUpdated: '2026-01-05',
    keterangan: 'MoU terminal batubara. EXPIRED — proses renewal sedang berjalan.',
  },
  {
    id: 'c008',
    nomorKontrak: 'HK.01/PKS/008/PLND-REG2/2025',
    mitra: 'PT Pelayaran Nasional Indonesia',
    mitraId: 'p008',
    jenisKontrak: 'PKS',
    nilaiKontrak: 5100000000,
    tanggalMulai: '2025-06-01',
    tanggalAkhir: '2027-05-31',
    sisaHari: 442,
    status: 'Aktif',
    complianceScore: 93,
    missingClauses: [],
    picInternal: 'Siti Mardiyah',
    region: 'Palembang',
    kategori: 'Pemanduan & Penundaan Kapal',
    pnbpValue: 760000000,
    lastUpdated: '2026-03-11',
    keterangan: 'PKS layanan pemanduan PELNI. Semua klausul terpenuhi.',
  },
  {
    id: 'c009',
    nomorKontrak: 'HK.01/PKS/009/PLND-REG2/2025',
    mitra: 'PT Chevron Pacific Indonesia',
    mitraId: 'p009',
    jenisKontrak: 'PKS',
    nilaiKontrak: 9200000000,
    tanggalMulai: '2025-03-15',
    tanggalAkhir: '2026-05-14',
    sisaHari: 60,
    status: 'Mendekati Akhir',
    complianceScore: 79,
    missingClauses: ['Program Fit to Work', 'Klausul CSMS'],
    picInternal: 'Reza Firmansyah',
    region: 'Jambi',
    kategori: 'Pemanduan & Penundaan Kapal',
    pnbpValue: 1380000000,
    lastUpdated: '2026-03-13',
    keterangan: 'PKS pemanduan kapal Chevron. CSMS dan Fit to Work perlu dilengkapi.',
  },
  {
    id: 'c010',
    nomorKontrak: 'HK.01/TUKS/010/PLND-REG2/2024',
    mitra: 'PT Pupuk Sriwidjaja Palembang',
    mitraId: 'p010',
    jenisKontrak: 'TUKS',
    nilaiKontrak: 18600000000,
    tanggalMulai: '2024-06-01',
    tanggalAkhir: '2029-05-31',
    sisaHari: 1173,
    status: 'Aktif',
    complianceScore: 98,
    missingClauses: [],
    picInternal: 'Budi Santoso',
    region: 'Palembang',
    kategori: 'TUKS (Terminal Untuk Kepentingan Sendiri)',
    pnbpValue: 3200000000,
    lastUpdated: '2026-03-14',
    keterangan: 'TUKS terminal pupuk Pusri. Compliance sempurna, kontrak 5 tahun.',
  },
  {
    id: 'c011',
    nomorKontrak: 'HK.01/PKS/011/PLND-REG2/2025',
    mitra: 'PT Indah Kiat Pulp & Paper',
    mitraId: 'p011',
    jenisKontrak: 'PKS',
    nilaiKontrak: 4200000000,
    tanggalMulai: '2025-11-01',
    tanggalAkhir: '2026-10-31',
    sisaHari: 230,
    status: 'Review Legal',
    complianceScore: 55,
    missingClauses: ['Klausul K3 (SMK3)', 'Klausul GCG', 'Klausul PNBP', 'Audit BPK Readiness'],
    picInternal: 'Ahmad Fauzi',
    region: 'Banten',
    kategori: 'Pemanfaatan Lahan',
    pnbpValue: 0,
    lastUpdated: '2026-03-14',
    keterangan: 'Dalam proses review legal. 4 klausul wajib belum ada — perlu perbaikan segera.',
  },
];

export const partners: Partner[] = [
  {
    id: 'p001',
    namaPerusahaan: 'PetroChina International Jabung Ltd.',
    npwp: '01.234.567.8-901.000',
    segmenBisnis: 'Migas',
    picInternal: 'Ahmad Fauzi',
    kontrakAktif: 1,
    totalNilaiKontrak: 8750000000,
    complianceScore: 72,
    status: 'Mitra Aktif',
    skorPeluang: 88,
    region: 'Jambi',
    kontakUtama: 'James Hendrick',
    jabatanKontak: 'Operations Manager',
    email: 'j.hendrick@petrochina-jabung.com',
    telepon: '+62 741 5501234',
    alamat: 'Jl. Gatot Subroto No. 28, Jambi',
    bergabungSejak: '2019-03-01',
    lastInteraction: '2026-03-10',
    ratingK3: 'B',
    totalKontrak: 3,
    renewalRate: 100,
    catatan: 'Mitra strategis migas. Kontrak mendekati akhir, peluang renewal tinggi.',
  },
  {
    id: 'p002',
    namaPerusahaan: 'PT Dok Usaha Sejahtera Bengkulu',
    npwp: '02.345.678.9-012.000',
    segmenBisnis: 'Kepelabuhanan',
    picInternal: 'Dewi Rahayu',
    kontrakAktif: 1,
    totalNilaiKontrak: 2400000000,
    complianceScore: 85,
    status: 'Mitra Aktif',
    skorPeluang: 72,
    region: 'Bengkulu',
    kontakUtama: 'Hendra Kusuma',
    jabatanKontak: 'Direktur Operasional',
    email: 'hendra@dusb.co.id',
    telepon: '+62 736 21456',
    alamat: 'Jl. Pelabuhan No. 5, Bengkulu',
    bergabungSejak: '2022-01-15',
    lastInteraction: '2026-03-12',
    ratingK3: 'A',
    totalKontrak: 2,
    renewalRate: 100,
    catatan: 'Mitra andal fasilitas pelabuhan Bengkulu. Rekam jejak baik.',
  },
  {
    id: 'p003',
    namaPerusahaan: 'PT Pertamina Trans Kontinental',
    npwp: '03.456.789.0-123.000',
    segmenBisnis: 'Migas',
    picInternal: 'Budi Santoso',
    kontrakAktif: 1,
    totalNilaiKontrak: 15200000000,
    complianceScore: 96,
    status: 'Mitra Aktif',
    skorPeluang: 95,
    region: 'Palembang',
    kontakUtama: 'Ir. Wahyu Prasetyo',
    jabatanKontak: 'VP Operasi',
    email: 'w.prasetyo@ptk.pertamina.com',
    telepon: '+62 711 445566',
    alamat: 'Jl. Merdeka No. 12, Palembang',
    bergabungSejak: '2018-07-01',
    lastInteraction: '2026-03-08',
    ratingK3: 'A',
    totalKontrak: 5,
    renewalRate: 100,
    catatan: 'Mitra tier-1. TUKS utama Palembang. Compliance sempurna.',
  },
  {
    id: 'p004',
    namaPerusahaan: 'PT Semen Baturaja (Persero) Tbk.',
    npwp: '04.567.890.1-234.000',
    segmenBisnis: 'Industri',
    picInternal: 'Siti Mardiyah',
    kontrakAktif: 1,
    totalNilaiKontrak: 4600000000,
    complianceScore: 90,
    status: 'Mitra Aktif',
    skorPeluang: 80,
    region: 'Palembang',
    kontakUtama: 'Drs. Agus Triyono',
    jabatanKontak: 'GM Logistik',
    email: 'a.triyono@semenbaturaja.co.id',
    telepon: '+62 711 554433',
    alamat: 'Jl. Industri No. 8, Baturaja',
    bergabungSejak: '2021-04-01',
    lastInteraction: '2026-03-05',
    ratingK3: 'A',
    totalKontrak: 3,
    renewalRate: 100,
    catatan: 'BUMN mitra strategis. Peluang ekspansi layanan curah kering.',
  },
  {
    id: 'p005',
    namaPerusahaan: 'PT Medco Energi Internasional',
    npwp: '05.678.901.2-345.000',
    segmenBisnis: 'Migas',
    picInternal: 'Ahmad Fauzi',
    kontrakAktif: 1,
    totalNilaiKontrak: 6300000000,
    complianceScore: 61,
    status: 'Evaluasi',
    skorPeluang: 55,
    region: 'Palembang',
    kontakUtama: 'Bambang Widianto',
    jabatanKontak: 'Head of Marine',
    email: 'b.widianto@medco.co.id',
    telepon: '+62 711 778899',
    alamat: 'Jl. Veteran No. 45, Palembang',
    bergabungSejak: '2020-09-01',
    lastInteraction: '2026-03-08',
    ratingK3: 'C',
    totalKontrak: 2,
    renewalRate: 50,
    catatan: 'PERINGATAN: 3 klausul K3 wajib belum ada. Perlu tindakan sebelum renewal.',
  },
  {
    id: 'p006',
    namaPerusahaan: 'PT Krakatau Steel (Persero) Tbk.',
    npwp: '06.789.012.3-456.000',
    segmenBisnis: 'Industri',
    picInternal: 'Reza Firmansyah',
    kontrakAktif: 1,
    totalNilaiKontrak: 3900000000,
    complianceScore: 88,
    status: 'Mitra Aktif',
    skorPeluang: 75,
    region: 'Banten',
    kontakUtama: 'Ir. Slamet Widodo',
    jabatanKontak: 'Direktur Logistik',
    email: 's.widodo@krakatausteel.co.id',
    telepon: '+62 254 382200',
    alamat: 'Jl. Industri No. 1, Cilegon, Banten',
    bergabungSejak: '2022-02-01',
    lastInteraction: '2026-03-07',
    ratingK3: 'B',
    totalKontrak: 2,
    renewalRate: 100,
    catatan: 'BUMN baja. GCG clause perlu update di kontrak aktif.',
  },
  {
    id: 'p007',
    namaPerusahaan: 'PT Bukit Asam Tbk.',
    npwp: '07.890.123.4-567.000',
    segmenBisnis: 'Industri',
    picInternal: 'Dewi Rahayu',
    kontrakAktif: 0,
    totalNilaiKontrak: 11500000000,
    complianceScore: 78,
    status: 'Evaluasi',
    skorPeluang: 90,
    region: 'Palembang',
    kontakUtama: 'Dr. Arif Budiman',
    jabatanKontak: 'SVP Operasi',
    email: 'a.budiman@bukitasam.co.id',
    telepon: '+62 711 312233',
    alamat: 'Jl. Parigi No. 1, Tanjung Enim',
    bergabungSejak: '2017-01-01',
    lastInteraction: '2026-03-03',
    ratingK3: 'B',
    totalKontrak: 4,
    renewalRate: 75,
    catatan: 'Kontrak expired. Proses renewal aktif — nilai tinggi, prioritaskan.',
  },
  {
    id: 'p008',
    namaPerusahaan: 'PT Pelayaran Nasional Indonesia',
    npwp: '08.901.234.5-678.000',
    segmenBisnis: 'Kepelabuhanan',
    picInternal: 'Siti Mardiyah',
    kontrakAktif: 1,
    totalNilaiKontrak: 5100000000,
    complianceScore: 93,
    status: 'Mitra Aktif',
    skorPeluang: 82,
    region: 'Palembang',
    kontakUtama: 'Capt. Darmawan Putra',
    jabatanKontak: 'GM Operasional',
    email: 'd.putra@pelni.co.id',
    telepon: '+62 711 445511',
    alamat: 'Jl. Merdeka No. 38, Palembang',
    bergabungSejak: '2020-06-01',
    lastInteraction: '2026-03-11',
    ratingK3: 'A',
    totalKontrak: 3,
    renewalRate: 100,
    catatan: 'BUMN pelayaran. Rekam jejak compliance sangat baik.',
  },
  {
    id: 'p009',
    namaPerusahaan: 'PT Chevron Pacific Indonesia',
    npwp: '09.012.345.6-789.000',
    segmenBisnis: 'Migas',
    picInternal: 'Reza Firmansyah',
    kontrakAktif: 1,
    totalNilaiKontrak: 9200000000,
    complianceScore: 79,
    status: 'Mitra Aktif',
    skorPeluang: 85,
    region: 'Jambi',
    kontakUtama: 'Richard Tan',
    jabatanKontak: 'Marine Superintendent',
    email: 'r.tan@chevron.com',
    telepon: '+62 741 6623456',
    alamat: 'Jl. Sudirman No. 77, Jambi',
    bergabungSejak: '2021-03-15',
    lastInteraction: '2026-03-13',
    ratingK3: 'B',
    totalKontrak: 2,
    renewalRate: 100,
    catatan: 'Mitra migas internasional. CSMS dan Fit to Work perlu dilengkapi.',
  },
  {
    id: 'p010',
    namaPerusahaan: 'PT Pupuk Sriwidjaja Palembang',
    npwp: '10.123.456.7-890.000',
    segmenBisnis: 'Industri',
    picInternal: 'Budi Santoso',
    kontrakAktif: 1,
    totalNilaiKontrak: 18600000000,
    complianceScore: 98,
    status: 'Mitra Aktif',
    skorPeluang: 97,
    region: 'Palembang',
    kontakUtama: 'Ir. Eko Prasetyo, MM',
    jabatanKontak: 'Direktur Operasi',
    email: 'e.prasetyo@pusri.co.id',
    telepon: '+62 711 712345',
    alamat: 'Jl. Mayor Zen, Palembang',
    bergabungSejak: '2016-06-01',
    lastInteraction: '2026-03-14',
    ratingK3: 'A',
    totalKontrak: 6,
    renewalRate: 100,
    catatan: 'Mitra BUMN tier-1 terbaik. TUKS terminal pupuk, compliance sempurna.',
  },
];

export const activityLogs: ActivityLog[] = [
  {
    id: 'a001',
    timestamp: '2026-03-15 08:32',
    type: 'alert',
    title: 'Alert Compliance Kritis',
    description: 'PKS PT Medco Energi (HK.01/PKS/005) — 3 klausul K3 wajib belum ada. Sisa 31 hari.',
    user: 'Sistem',
    kontrakId: 'c005',
    mitraName: 'PT Medco Energi Internasional',
  },
  {
    id: 'a002',
    timestamp: '2026-03-14 15:47',
    type: 'review',
    title: 'Dokumen Dikirim ke Review Legal',
    description: 'PKS PT Indah Kiat (HK.01/PKS/011) dikirim untuk review tim legal.',
    user: 'Ahmad Fauzi',
    kontrakId: 'c011',
    mitraName: 'PT Indah Kiat Pulp & Paper',
  },
  {
    id: 'a003',
    timestamp: '2026-03-14 11:20',
    type: 'upload',
    title: 'Dokumen Sertifikat K3 Diupload',
    description: 'Sertifikat SMK3 & ISO 45001 PT Pupuk Sriwidjaja diperbarui.',
    user: 'Budi Santoso',
    kontrakId: 'c010',
    mitraName: 'PT Pupuk Sriwidjaja Palembang',
  },
  {
    id: 'a004',
    timestamp: '2026-03-13 09:15',
    type: 'reminder',
    title: 'Reminder: Kontrak Mendekati Akhir',
    description: 'PKS Chevron Pacific (HK.01/PKS/009) — 60 hari tersisa. Siapkan proses renewal.',
    user: 'Sistem',
    kontrakId: 'c009',
    mitraName: 'PT Chevron Pacific Indonesia',
  },
  {
    id: 'a005',
    timestamp: '2026-03-12 16:05',
    type: 'approval',
    title: 'Kontrak Disetujui Senior Manager',
    description: 'Addendum PT Semen Baturaja (HK.01/ADD/004) mendapat persetujuan SM.',
    user: 'Ir. Hendra Wijaya (SM)',
    kontrakId: 'c004',
    mitraName: 'PT Semen Baturaja (Persero) Tbk.',
  },
  {
    id: 'a006',
    timestamp: '2026-03-10 14:30',
    type: 'renewal',
    title: 'Proses Renewal Dimulai',
    description: 'PKS PetroChina Jabung (HK.01/PKS/001) — proses renewal 2026-2028 dimulai.',
    user: 'Ahmad Fauzi',
    kontrakId: 'c001',
    mitraName: 'PetroChina International Jabung Ltd.',
  },
];

export const complianceTrendData = [
  { bulan: 'Apr', rate: 71, kontrakBaru: 2 },
  { bulan: 'Mei', rate: 73, kontrakBaru: 1 },
  { bulan: 'Jun', rate: 69, kontrakBaru: 3 },
  { bulan: 'Jul', rate: 74, kontrakBaru: 1 },
  { bulan: 'Agu', rate: 76, kontrakBaru: 2 },
  { bulan: 'Sep', rate: 79, kontrakBaru: 0 },
  { bulan: 'Okt', rate: 81, kontrakBaru: 2 },
  { bulan: 'Nov', rate: 78, kontrakBaru: 1 },
  { bulan: 'Des', rate: 82, kontrakBaru: 3 },
  { bulan: 'Jan', rate: 80, kontrakBaru: 1 },
  { bulan: 'Feb', rate: 83, kontrakBaru: 2 },
  { bulan: 'Mar', rate: 81, kontrakBaru: 1 },
];

export const contractTypeData = [
  { jenis: 'PKS', jumlah: 6, nilai: 49550000000 },
  { jenis: 'MoU', jumlah: 2, nilai: 13900000000 },
  { jenis: 'TUKS', jumlah: 1, nilai: 18600000000 },
  { jenis: 'Addendum', jumlah: 1, nilai: 4600000000 },
  { jenis: 'Pemanfaatan Lahan', jumlah: 1, nilai: 3900000000 },
];

export const statusDistributionData = [
  { name: 'Aktif', value: 6, fill: '#16a34a' },
  { name: 'Mendekati Akhir', value: 4, fill: '#d97706' },
  { name: 'Expired', value: 1, fill: '#dc2626' },
  { name: 'Review Legal', value: 1, fill: '#2563eb' },
  { name: 'Renewal', value: 1, fill: '#0891b2' },
];

export function formatRupiah(value: number): string {
  if (value >= 1_000_000_000) {
    return `Rp ${(value / 1_000_000_000).toFixed(1)} M`;
  }
  if (value >= 1_000_000) {
    return `Rp ${(value / 1_000_000).toFixed(0)} Jt`;
  }
  return `Rp ${value.toLocaleString('id-ID')}`;
}

export function formatRupiahFull(value: number): string {
  return `Rp ${value.toLocaleString('id-ID')}`;
}